Repository somul-project/somul-system-frontend, pull requests merged in 2020-05, with the labels that each got.

#26 feat: signin & up 페이지 구현
  .eslintrc.json
  .gitignore
  package.json
  public/etc/dropdown-box.svg
  public/illust/signup-illustration.png
  public/logo/email.svg
  public/logo/github.svg
  public/warning.svg
  src/App.test.tsx
  src/App.tsx
  src/frameworks/web/components/atoms/Label/Label.tsx
  src/frameworks/web/components/atoms/LoginButton/LoginButton.stories.tsx
  src/frameworks/web/components/atoms/LoginButton/LoginButton.tsx
  src/frameworks/web/components/atoms/SignButton/SignButton.stories.tsx
  src/frameworks/web/components/atoms/SignButton/SignButton.tsx
  src/frameworks/web/components/atoms/TextArea/TextArea.tsx
  src/frameworks/web/components/atoms/TextField/TextField.stories.tsx
  src/frameworks/web/components/atoms/TextField/TextField.tsx
  src/frameworks/web/components/molecules/DividedCard/DividedCard.tsx
  src/frameworks/web/components/molecules/NavigationBar/NavigationBar.stories.tsx
  src/frameworks/web/components/molecules/NavigationBar/NavigationBar.tsx
  src/frameworks/web/components/molecules/SingleCard/SingleCard.tsx
  src/frameworks/web/components/organisms/Header/Header.tsx
  src/frameworks/web/components/organisms/SignIn/ChangeComplete.tsx
  src/frameworks/web/components/organisms/SignIn/ChangePassword.tsx
  src/frameworks/web/components/organisms/SignIn/ForgotComplete.tsx
  src/frameworks/web/components/organisms/SignIn/ForgotPassword.tsx
  src/frameworks/web/components/organisms/SignIn/SignInCard.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpCard.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpComplete.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpNow.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpOAuth.tsx
  src/frameworks/web/components/pages/Landing/Landing.tsx
  src/frameworks/web/components/pages/SignIn/SignIn.tsx
  src/frameworks/web/components/pages/SignUp/SignUp.tsx
  src/frameworks/web/redux/reducers/index.ts
  src/frameworks/web/redux/reducers/session.ts
  src/frameworks/web/redux/store/index.ts
  src/interfaces/frameworks/session.ts
  src/interfaces/frameworks/web/components/atoms/LoginButton/ILoginButton.ts
  src/interfaces/frameworks/web/components/atoms/SignButton/ISignButton.ts
  src/interfaces/frameworks/web/components/atoms/TextArea/ITextArea.ts
  src/interfaces/frameworks/web/components/atoms/TextField/ITextField.ts
  src/interfaces/frameworks/web/components/molecules/DividedCard/IDividedCard.ts
  src/interfaces/frameworks/web/components/molecules/NavigationBar/INavigationBar.ts
  src/interfaces/frameworks/web/components/organisms/SignIn/IChange.ts
  src/interfaces/frameworks/web/components/organisms/SignIn/IForgot.ts
  src/interfaces/frameworks/web/components/organisms/SignUp/ISignUpOAuth.ts
  src/interfaces/utils/user/IUserService.ts
  src/utils/constants.ts
  src/utils/user.test.tsx
  src/utils/user.ts
  yarn.lock
Labels: ui:page

#31 feat: 발표자 신청 플로우 뷰 추가
  public/icon/add-circle.svg
  public/icon/highlight-off.svg
  public/illust/speaker-apply-illustration.png
  src/App.tsx
  src/frameworks/web/components/atoms/SignButton/SignButton.tsx
  src/frameworks/web/components/atoms/TextArea/TextArea.tsx
  src/frameworks/web/components/atoms/TextField/TextField.stories.tsx
  src/frameworks/web/components/atoms/TextField/TextField.tsx
  src/frameworks/web/components/molecules/NavigationBar/NavigationBar.tsx
  src/frameworks/web/components/organisms/Header/Header.tsx
  src/frameworks/web/components/organisms/Landing/LandingJoin.tsx
  src/frameworks/web/components/organisms/SignIn/ChangeComplete.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpNow.tsx
  src/frameworks/web/components/organisms/SpeakerApply/SpeakerApplyComplete.tsx
  src/frameworks/web/components/organisms/SpeakerApply/SpeakerApplyStep1.tsx
  src/frameworks/web/components/organisms/SpeakerApply/SpeakerApplyStep2.tsx
  src/frameworks/web/components/pages/SpeakerApply/SpeakerApply.tsx
  src/interfaces/frameworks/web/components/atoms/TextArea/ITextArea.ts
  src/interfaces/frameworks/web/components/atoms/TextField/ITextField.ts
  src/interfaces/frameworks/web/components/organisms/SpeakerApply/ISpeakerApplyStep1.ts
  src/interfaces/frameworks/web/components/organisms/SpeakerApply/ISpeakerApplyStep2.ts
  src/interfaces/frameworks/web/components/pages/SpeakerApply/ISpeakerApply.ts
  src/utils/form.ts
  src/utils/user.test.tsx
  src/utils/user.ts
Labels: ui:component, ui:page

#50 Refactor: Atom component를 Functional Component로 변경
  src/frameworks/web/components/atoms/Button/Button.tsx
  src/frameworks/web/components/atoms/CheckBox/CheckBox.tsx
  src/frameworks/web/components/atoms/ContentSwitcher/ContentSwitcher.tsx
  src/frameworks/web/components/atoms/ContentsBox/ContentsBox.tsx
  src/frameworks/web/components/atoms/Label/Label.tsx
  src/frameworks/web/components/atoms/RadioButton/RadioButton.tsx
  src/frameworks/web/components/atoms/SearchField/SearchField.tsx
  src/frameworks/web/components/atoms/Select/Select.tsx
  src/frameworks/web/components/atoms/SignButton/SignButton.tsx
  src/frameworks/web/components/atoms/Tag/Tag.tsx
  src/frameworks/web/components/atoms/TextArea/TextArea.tsx
  src/frameworks/web/components/atoms/TextField/TextField.tsx
  src/interfaces/frameworks/web/components/atoms/Button/IButton.ts
  src/interfaces/frameworks/web/components/atoms/Label/ILabel.ts
Labels: refactoring, ui:component, ui:page

#56 chore: serviceWorker.ts 컴파일 에러 해결
  src/serviceWorker.ts
Labels: bug

#57 feat: 회원가입 / 로그인 비즈니스 로직 리팩토링, 구조 설계
  .env
  craco.config.js
  package.json
  png.d.ts
  src/App.css
  src/App.tsx
  src/adapters/infrastructures/.gitkeep
  src/adapters/presenters/.gitkeep
  src/adapters/presenters/di/.gitkeep
  src/adapters/repositories/.gitkeep
  src/assets/illust/signup-illustration.png
  src/assets/logo/codeclub.svg
  src/assets/logo/email.svg
  src/assets/logo/facebook-footer.svg
  src/assets/logo/github-footer.svg
  src/assets/logo/github.svg
  src/assets/logo/google.svg
  src/assets/logo/logo.svg
  src/domains/entities/.gitkeep
  src/domains/usecases/.gitkeep
  src/domains/usecases/di/.gitkeep
  src/domains/vos/.gitkeep
  src/frameworks/web/apollo/index.ts
  src/frameworks/web/components/atoms/Button/Button.tsx
  src/frameworks/web/components/atoms/Loading/Loading.stories.tsx
  src/frameworks/web/components/atoms/Loading/Loading.tsx
  src/frameworks/web/components/atoms/SignButton/SignButton.tsx
  src/frameworks/web/components/atoms/TextField/TextField.stories.tsx
  src/frameworks/web/components/atoms/TextField/TextField.tsx
  src/frameworks/web/components/organisms/Footer/Footer.tsx
  src/frameworks/web/components/organisms/Header/Header.tsx
  src/frameworks/web/components/organisms/SignIn/SignInCard.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpCard.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpComplete.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpNow.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpOAuth.tsx
  src/frameworks/web/components/organisms/SpeakerApply/SpeakerApplyStep1.tsx
  src/frameworks/web/components/organisms/SpeakerApply/SpeakerApplyStep2.tsx
  src/frameworks/web/components/pages/SignIn/SignIn.tsx
  src/frameworks/web/components/pages/SignUp/SignUp.tsx
  src/interfaces/frameworks/web/components/atoms/Button/IButton.ts
  src/interfaces/frameworks/web/components/atoms/TextField/ITextField.ts
  src/interfaces/service/request/ISignInRequest.ts
  src/interfaces/service/request/ISignUpRequest.ts
  src/interfaces/utils/IValidator.ts
  src/interfaces/utils/user/IUserService.ts
  src/logo.svg
  src/service/query/SignInQuery.ts
  src/service/query/SignUpQuery.ts
  src/service/request/SignInRequest.ts
  src/service/request/SignUpRequest.ts
  src/utils/constants.ts
  src/utils/form.ts
  src/utils/user.test.tsx
  src/utils/user.ts
  src/utils/validator.ts
  svg.d.ts
  tsconfig.json
  tsconfig.paths.json
  yarn.lock
Labels: api, enhancement, refactoring

#52 Refactor: Molecule component를 Functional Component로 변경
  src/frameworks/web/components/molecules/DividedCard/DividedCard.tsx
  src/frameworks/web/components/molecules/RadioGroup/RadioGroup.tsx
  src/frameworks/web/components/molecules/SingleCard/SingleCard.tsx
  src/interfaces/frameworks/web/components/molecules/SingleCard/ISingleCard.ts
Labels: refactoring, ui:component

#55 chore: Modal 컴포넌트 추가
  public/icon/x.svg
  src/frameworks/web/components/molecules/Modal/Modal.stories.tsx
  src/frameworks/web/components/molecules/Modal/Modal.tsx
  src/interfaces/frameworks/web/components/molecules/Modal/IModal.ts
Labels: ui:component

#51 chore: Github Actions CI 추가
  .github/workflows/ci.yml
Labels: enhancement

#58 feat: 강연 신청하지 않았을 경우 Status 페이지 추가
  src/App.tsx
  src/frameworks/web/components/pages/StatusPage/StatusPage.tsx
  src/interfaces/frameworks/web/components/pages/StatusPage/IStatusPage.ts
  src/utils/constants.ts
Labels: ui:page

#53 refactor: Organism component를 Functional Component로 변경
  src/App.tsx
  src/assets/icon/mobile-menu.svg
  src/assets/illust/about-illustration.png
  src/assets/illust/main-illustration.png
  src/assets/illust/speaker-apply-illustration.png
  src/assets/illust/speaker-illustration.png
  src/assets/illust/sponsor-illustration.png
  src/frameworks/web/components/organisms/.gitkeep
  src/frameworks/web/components/organisms/Footer/Footer.tsx
  src/frameworks/web/components/organisms/Header/Header.tsx
  src/frameworks/web/components/organisms/Landing/LandingAbout.tsx
  src/frameworks/web/components/organisms/Landing/LandingBanner.tsx
  src/frameworks/web/components/organisms/Landing/LandingJoin.tsx
  src/frameworks/web/components/organisms/Landing/LandingSponsor.tsx
  src/frameworks/web/components/organisms/SignIn/ChangeComplete.tsx
  src/frameworks/web/components/organisms/SignIn/ChangePassword.tsx
  src/frameworks/web/components/organisms/SignIn/ForgotComplete.tsx
  src/frameworks/web/components/organisms/SignIn/ForgotPassword.tsx
  src/frameworks/web/components/organisms/SignIn/SignInCard.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpCard.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpComplete.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpOAuth.tsx
  src/frameworks/web/components/organisms/SpeakerApply/SpeakerApplyComplete.tsx
  src/frameworks/web/components/pages/SignIn/SignIn.tsx
  src/frameworks/web/components/pages/SignUp/SignUp.tsx
  src/frameworks/web/components/pages/SpeakerApply/SpeakerApply.tsx
  src/interfaces/frameworks/web/components/organisms/Header/IHeader.ts
  src/utils/constants.ts
  src/utils/routes.ts
  src/utils/validator.ts
Labels: refactoring, ui:page

#63 feat: YouTube URL validator 추가
  src/utils/validator.ts
Labels: new-feature

#64 chore: GraphQL 사용을 위한 폴더 구조 생성
  package.json
  src/frameworks/web/apollo/index.ts
  src/frameworks/web/components/organisms/SignUp/SignUpComplete.tsx
  src/frameworks/web/redux/reducers/index.ts
  src/frameworks/web/redux/reducers/session.ts
  src/frameworks/web/redux/store/index.ts
  src/frameworks/web/store/.gitkeep
  src/interfaces/frameworks/session.ts
  src/interfaces/service/graphql/mutation/.gitkeep
  src/interfaces/service/graphql/query/IUser.ts
  src/interfaces/service/graphql/schema/ILibrary.ts
  src/interfaces/service/graphql/schema/IMutation.ts
  src/interfaces/service/graphql/schema/ISession.ts
  src/interfaces/service/graphql/schema/IUser.ts
  src/interfaces/service/graphql/schema/IVolunteer.ts
  src/service/graphql/mutation/User.ts
  src/service/graphql/query/User.ts
  src/service/graphql/rest/SignInQuery.ts
  src/service/graphql/rest/SignUpQuery.ts
  src/service/request/SignInRequest.ts
  src/service/request/SignUpRequest.ts
  yarn.lock
Labels: enhancement

#66 fix: 보여주는 화면의 높이가 짧을 경우 footer가 재 위치에 있지 않는 오류 수정
  src/frameworks/web/components/pages/SignIn/SignIn.tsx
  src/frameworks/web/components/pages/SignUp/SignUp.tsx
  src/frameworks/web/components/pages/SpeakerApply/SpeakerApply.tsx
  src/frameworks/web/components/pages/StatusPage/StatusPage.tsx
Labels: bug, ui:page

#62 feat: 신청현황 페이지에 '신청한 강연이 있을 경우' 뷰 디자인 구현
  src/assets/icon/play.svg
  src/frameworks/web/components/atoms/VideoButton/VideoButton.stories.tsx
  src/frameworks/web/components/atoms/VideoButton/VideoButton.tsx
  src/frameworks/web/components/organisms/StatusPage/StatusContent.tsx
  src/frameworks/web/components/pages/StatusPage/StatusPage.tsx
  src/interfaces/frameworks/web/components/atoms/VideoButton/IVideoButton.ts
  src/interfaces/frameworks/web/components/organisms/StatusPage/IStatusContent.ts
Labels: ui:component, ui:page

#70 fix: 특정 화면에서 로딩 컴포넌트가 한쪽으로 쏠리는 오류 수정
  src/frameworks/web/components/organisms/SignIn/SignInCard.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpComplete.tsx
Labels: bug, ui:page

#59 feat: 프로필 페이지 뷰 추가
  src/App.tsx
  src/frameworks/web/components/atoms/Button/Button.stories.tsx
  src/frameworks/web/components/atoms/Button/Button.tsx
  src/frameworks/web/components/atoms/TextField/TextField.tsx
  src/frameworks/web/components/organisms/Profile/ProfileInfo.tsx
  src/frameworks/web/components/organisms/Profile/ProfileWithdraw.tsx
  src/frameworks/web/components/pages/Profile/Profile.tsx
  src/interfaces/frameworks/web/components/atoms/Button/IButton.ts
  src/interfaces/frameworks/web/components/organisms/Profile/IProfileInfo.ts
  src/interfaces/frameworks/web/components/pages/Profile/IProfile.ts
  src/utils/routes.ts
Labels: new-feature, ui:page

#68 fix: 헤더 관련 오류 수정
  package.json
  src/frameworks/web/components/organisms/Header/Header.tsx
  src/frameworks/web/components/organisms/Landing/LandingBanner.tsx
  src/frameworks/web/components/pages/Landing/Landing.tsx
  yarn.lock
Labels: bug, ui:component, ui:page

#67 feat: 로그인 했을 경우, 헤더에 유저 정보를 표시하는 기능 추가
  package.json
  src/assets/etc/dropdown-box.svg
  src/assets/icon/arrow-down.svg
  src/assets/icon/person.svg
  src/frameworks/web/components/atoms/Loading/Loading.tsx
  src/frameworks/web/components/molecules/.gitkeep
  src/frameworks/web/components/molecules/NavigationBar/NavigationBar.tsx
  src/frameworks/web/components/organisms/Header/Header.tsx
  src/frameworks/web/components/pages/.gitkeep
  src/frameworks/web/components/templates/.gitkeep
  src/frameworks/web/hooks/CurrentSessionHook.ts
  src/interfaces/frameworks/web/components/atoms/Loading/ILoading.ts
  src/interfaces/frameworks/web/components/molecules/NavigationBar/INavigationBar.ts
  src/interfaces/service/graphql/schema/ILoginSession.ts
  src/service/graphql/rest/GetSessionQuery.ts
  src/service/graphql/rest/SignOutQuery.ts
  src/service/request/CurrentSessionRequest.ts
  yarn.lock
Labels: new-feature, ui:component

#71 chore: 프로젝트에서 사용되던 alert를 Modal로 변경 및 제거
  src/frameworks/web/components/molecules/Modal/Modal.stories.tsx
  src/frameworks/web/components/molecules/NavigationBar/NavigationBar.tsx
  src/frameworks/web/components/organisms/SignIn/SignInCard.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpComplete.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpNow.tsx
  src/utils/routes.ts
Labels: enhancement, ui:component, ui:page

#65 feat: 강연자 신청 페이지 개발
  src/App.tsx
  src/assets/icon/add-circle.svg
  src/assets/icon/highlight-off.svg
  src/frameworks/web/components/atoms/TextArea/TextArea.tsx
  src/frameworks/web/components/atoms/TextField/TextField.tsx
  src/frameworks/web/components/molecules/DividedCard/DividedCard.tsx
  src/frameworks/web/components/molecules/NavigationBar/NavigationBar.tsx
  src/frameworks/web/components/organisms/SpeakerApply/SpeakerApplyComplete.tsx
  src/frameworks/web/components/organisms/SpeakerApply/SpeakerApplyForm.tsx
  src/frameworks/web/components/organisms/SpeakerApply/SpeakerApplyStep1.tsx
  src/frameworks/web/components/organisms/SpeakerApply/SpeakerApplyStep2.tsx
  src/frameworks/web/components/pages/SpeakerApply/SpeakerApply.tsx
  src/interfaces/frameworks/web/components/atoms/TextArea/ITextArea.ts
  src/interfaces/frameworks/web/components/atoms/TextField/ITextField.ts
  src/interfaces/service/graphql/mutation/ISession.ts
  src/interfaces/service/graphql/schema/IMutation.ts
  src/service/graphql/mutation/Session.ts
  src/service/graphql/query/User.ts
  src/utils/validator.ts
Labels: new-feature, ui:page

#73 fix: 소셜 계정으로 회원가입을 했을 때에도 이메일 / 비밀번호를 입력하는 화면이 나오는 문제 수정
  package.json
  src/assets/icon/warning.svg
  src/frameworks/web/components/atoms/Label/Label.tsx
  src/frameworks/web/components/molecules/NavigationBar/NavigationBar.tsx
  src/frameworks/web/components/organisms/Header/Header.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpCard.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpComplete.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpNow.tsx
  src/frameworks/web/components/organisms/SignUp/SignUpOAuth.tsx
  src/frameworks/web/components/pages/Landing/Landing.tsx
  src/frameworks/web/components/pages/Profile/Profile.tsx
  src/frameworks/web/components/pages/SignIn/SignIn.tsx
  src/frameworks/web/components/pages/SignUp/SignUp.tsx
  src/frameworks/web/hooks/CurrentSessionHook.ts
  src/interfaces/frameworks/web/components/atoms/Label/ILabel.ts
  src/utils/constants.ts
  yarn.lock
Labels: bug, enhancement, ui:page

#76 feat: 프로필 페이지 개발
  src/App.tsx
  src/frameworks/web/components/molecules/NavigationBar/NavigationBar.tsx
  src/frameworks/web/components/organisms/Profile/ProfileInfo.tsx
  src/frameworks/web/components/pages/Profile/Profile.tsx
  src/service/graphql/mutation/User.ts
Labels: new-feature

#83 feat: 세션에 따라 접근 가능한 페이지와 불가능한 페이지 관리
  src/frameworks/web/components/organisms/Header/Header.tsx
  src/frameworks/web/components/organisms/SignIn/ForgotPassword.tsx
Labels: new-feature

#87 fix: DividedCard가 오른쪽 구역에 맞지 않게 왼쪽 구역의 높이가 조절되지 않는 오류 수정
  src/frameworks/web/components/molecules/DividedCard/DividedCard.tsx
Labels: bug, ui:component

#110 chore: LectureModal 컴포넌트 추가
  src/frameworks/web/components/molecules/LectureModal/LectureModal.stories.tsx
  src/frameworks/web/components/molecules/LectureModal/LectureModal.tsx
  src/interfaces/frameworks/web/components/molecules/LectureModal/ILectureModal.ts
Labels: new-feature, ui:component

#107 fix: 로그인 페이지 화면 구성 수정
  src/frameworks/web/components/organisms/SignIn/SignInCard.tsx
Labels: bug, ui:page

#109 feat: 강연 목록 페이지 뷰 추가
  src/App.tsx
  src/assets/icon/search.svg
  src/assets/illust/list-illlustration.svg
  src/assets/logo/logo-white.svg
  src/frameworks/web/components/atoms/TextField/TextField.tsx
  src/frameworks/web/components/molecules/LectureCard/LectureCard.stories.tsx
  src/frameworks/web/components/molecules/LectureCard/LectureCard.tsx
  src/frameworks/web/components/organisms/Header/Header.tsx
  src/frameworks/web/components/organisms/Lecture/LectureList.tsx
  src/frameworks/web/components/pages/Lecture/Lecture.tsx
  src/interfaces/frameworks/web/components/molecules/LectureCard/ILectureCard.ts
  src/interfaces/frameworks/web/components/organisms/Lecture/ILectureList.ts
  src/utils/routes.ts
Labels: new-feature, ui:component, ui:page
